[versions]
activityKtx = "1.9.2"
agp = "8.5.2"
androidxEspressoCore = "3.4.0"
androidxJunit = "1.2.1"
androidxJunitVersion = "1.1.3"
androidxLifecycleViewmodelKtx = "2.8.6"
appcompatVersion = "1.7.0"
cardview = "1.0.0"
converterGson = "2.9.0"
core = "1.6.1"
coreKtxVersion = "1.12.0"
coreSplashscreen = "1.0.1"
coreTesting = "2.2.0"
espressoCoreVersion = "3.6.1"
firebaseAuth = "23.0.0"
firebaseAuthVersion = "21.0.1"
firebaseBom = "33.3.0"
firebaseDatabase = "21.0.0"
firebaseDatabaseVersion = "20.2.2"
hiltAndroid = "2.44"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
kotlinxCoroutinesPlayServices = "1.7.3"
kotlinxCoroutinesPlayServicesVersion = "1.6.4"
kotlinxCoroutinesTest = "1.5.1"
lifecycleViewmodelKtx = "2.4.1"
lifecycleViewmodelKtxVersion = "2.6.1"
loggingInterceptor = "4.9.3"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
materialVersion = "1.9.0"
mockitoCore = "4.5.1"
mockitoCoreVersion = "3.9.0"
mockitoInline = "3.9.0"
mockitoKotlinVersion = "<version>"
mockitoMockitoKotlin = "4.1.0"
picasso = "2.71828"
playServicesAuth = "21.2.0"
recyclerview = "1.3.2"
coordinatorlayout = "1.2.0"
recyclerviewVersion = "1.3.1"
roomCommon = "2.6.1"
roomCompiler = "2.5.0"
roomCompilerVersion = "2.6.1"
roomKtx = "2.6.1"
navigationFragmentKtx = "2.7.7"
roomKtxVersion = "2.5.1"
preference = "1.2.0"
preferenceKtx = "1.2.1"
media3Common = "1.4.1"
roomRuntime = "2.6.1"
navigationFragmentKtxVersion = "2.8.1"
navigationUiKtx = "2.8.1"
media3CommonKtx = "1.4.1"
workRuntimeKtx = "2.9.1"
coreI18n = "1.0.0-alpha01"
protoliteWellKnownTypes = "18.0.0"
firebaseFirestoreKtx = "25.1.1"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspressoCore" }
androidx-espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-junit-v113 = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
androidx-junit-v121 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-ktx-v261 = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
androidx-lifecycle-viewmodel-ktx-v286 = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycleViewmodelKtx" }
androidx-recyclerview-v131 = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtxVersion" }
androidx-room-compiler-v250 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-compiler-v261 = { module = "androidx.room:room-compiler", version.ref = "roomCompilerVersion" }
androidx-room-ktx-v251 = { module = "androidx.room:room-ktx", version.ref = "roomKtxVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtxVersion" }
androidx-room-runtime-v261 = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-auth-v2101 = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuthVersion" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabase" }
firebase-database-v2022 = { module = "com.google.firebase:firebase-database", version.ref = "firebaseDatabaseVersion" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlinVersion" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
kotlinx-coroutines-play-services-v164 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServicesVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesPlayServicesVersion" }
kotlinx-coroutines-test-v151 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }

material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-core-v390 = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin-v410 = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoMockitoKotlin" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-core-i18n = { group = "androidx.core", name = "core-i18n", version.ref = "coreI18n" }
protolite-well-known-types = { group = "com.google.firebase", name = "protolite-well-known-types", version.ref = "protoliteWellKnownTypes" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }




[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

